-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "name" character varying NOT NULL,
  "avatar_url" character varying NULL,
  "cognito_id" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

-- Create index "users_cognito_id_key" to table: "users"
CREATE UNIQUE INDEX "users_cognito_id_key" ON "public"."users" ("cognito_id");

-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");

-- Create "events" table
CREATE TABLE "public"."events" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "start_time" timestamptz NOT NULL,
  "end_time" timestamptz NOT NULL,
  "emoji" character varying NULL,
  "visibility" character varying NOT NULL DEFAULT 'private',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "user_created_events" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "events_users_created_events" FOREIGN KEY ("user_created_events") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Create "participants" table
CREATE TABLE "public"."participants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'viewer',
  "status" character varying NOT NULL DEFAULT 'pending',
  "joined_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "event_participants" bigint NOT NULL,
  "user_participants" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "participants_events_participants" FOREIGN KEY ("event_participants") REFERENCES "public"."events" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "participants_users_participants" FOREIGN KEY ("user_participants") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
