// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Participant is the predicate function for participant builders.
type Participant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
