version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  funlen:
    lines: 80
    statements: 40

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - funlen
    - lll

run:
  timeout: 5m
  skip-dirs:
    - tmp
    - vendor
    - node_modules

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - funlen
    - path: cmd/
      linters:
        - gocyclo
        - funlen
  max-issues-per-linter: 0
  max-same-issues: 0
