services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: morrow-postgres
    environment:
      POSTGRES_DB: morrow_dev
      POSTGRES_USER: morrow_user
      POSTGRES_PASSWORD: morrow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - morrow-network

  # Go Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: morrow-backend
    environment:
      - GO_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=morrow_dev
      - DB_USER=morrow_user
      - DB_PASSWORD=morrow_password
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go_cache:/go/pkg/mod
    depends_on:
      - postgres
    networks:
      - morrow-network
    command: ["sh", "-c", "while ! nc -z postgres 5432; do sleep 1; done && air -c .air.toml"]

  # React Native Frontend (Metro bundler)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: morrow-frontend
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "8081:8081"  # Metro bundler
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo DevTools
      - "19002:19002"  # Expo DevTools
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    networks:
      - morrow-network

  # Atlas Migration Service
  atlas:
    build:
      context: ./infrastructure/docker/atlas
      dockerfile: Dockerfile
    container_name: morrow-atlas
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=morrow_dev
      - POSTGRES_USER=morrow_user
      - POSTGRES_PASSWORD=morrow_password
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    networks:
      - morrow-network
    profiles:
      - tools

volumes:
  postgres_data:
  go_cache:
  node_modules_cache:

networks:
  morrow-network:
    driver: bridge
