// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/matsuokashuhei/morrow-backend/ent/event"
	"github.com/matsuokashuhei/morrow-backend/ent/participant"
	"github.com/matsuokashuhei/morrow-backend/ent/user"
)

// ParticipantCreate is the builder for creating a Participant entity.
type ParticipantCreate struct {
	config
	mutation *ParticipantMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (pc *ParticipantCreate) SetRole(pa participant.Role) *ParticipantCreate {
	pc.mutation.SetRole(pa)
	return pc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (pc *ParticipantCreate) SetNillableRole(pa *participant.Role) *ParticipantCreate {
	if pa != nil {
		pc.SetRole(*pa)
	}
	return pc
}

// SetStatus sets the "status" field.
func (pc *ParticipantCreate) SetStatus(pa participant.Status) *ParticipantCreate {
	pc.mutation.SetStatus(pa)
	return pc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pc *ParticipantCreate) SetNillableStatus(pa *participant.Status) *ParticipantCreate {
	if pa != nil {
		pc.SetStatus(*pa)
	}
	return pc
}

// SetJoinedAt sets the "joined_at" field.
func (pc *ParticipantCreate) SetJoinedAt(t time.Time) *ParticipantCreate {
	pc.mutation.SetJoinedAt(t)
	return pc
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (pc *ParticipantCreate) SetNillableJoinedAt(t *time.Time) *ParticipantCreate {
	if t != nil {
		pc.SetJoinedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *ParticipantCreate) SetUpdatedAt(t time.Time) *ParticipantCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *ParticipantCreate) SetNillableUpdatedAt(t *time.Time) *ParticipantCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pc *ParticipantCreate) SetUserID(id int) *ParticipantCreate {
	pc.mutation.SetUserID(id)
	return pc
}

// SetUser sets the "user" edge to the User entity.
func (pc *ParticipantCreate) SetUser(u *User) *ParticipantCreate {
	return pc.SetUserID(u.ID)
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (pc *ParticipantCreate) SetEventID(id int) *ParticipantCreate {
	pc.mutation.SetEventID(id)
	return pc
}

// SetEvent sets the "event" edge to the Event entity.
func (pc *ParticipantCreate) SetEvent(e *Event) *ParticipantCreate {
	return pc.SetEventID(e.ID)
}

// Mutation returns the ParticipantMutation object of the builder.
func (pc *ParticipantCreate) Mutation() *ParticipantMutation {
	return pc.mutation
}

// Save creates the Participant in the database.
func (pc *ParticipantCreate) Save(ctx context.Context) (*Participant, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ParticipantCreate) SaveX(ctx context.Context) *Participant {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ParticipantCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ParticipantCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *ParticipantCreate) defaults() {
	if _, ok := pc.mutation.Role(); !ok {
		v := participant.DefaultRole
		pc.mutation.SetRole(v)
	}
	if _, ok := pc.mutation.Status(); !ok {
		v := participant.DefaultStatus
		pc.mutation.SetStatus(v)
	}
	if _, ok := pc.mutation.JoinedAt(); !ok {
		v := participant.DefaultJoinedAt()
		pc.mutation.SetJoinedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := participant.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ParticipantCreate) check() error {
	if _, ok := pc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Participant.role"`)}
	}
	if v, ok := pc.mutation.Role(); ok {
		if err := participant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Participant.role": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Participant.status"`)}
	}
	if v, ok := pc.mutation.Status(); ok {
		if err := participant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Participant.status": %w`, err)}
		}
	}
	if _, ok := pc.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "Participant.joined_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Participant.updated_at"`)}
	}
	if len(pc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Participant.user"`)}
	}
	if len(pc.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "Participant.event"`)}
	}
	return nil
}

func (pc *ParticipantCreate) sqlSave(ctx context.Context) (*Participant, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ParticipantCreate) createSpec() (*Participant, *sqlgraph.CreateSpec) {
	var (
		_node = &Participant{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(participant.Table, sqlgraph.NewFieldSpec(participant.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Role(); ok {
		_spec.SetField(participant.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := pc.mutation.Status(); ok {
		_spec.SetField(participant.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := pc.mutation.JoinedAt(); ok {
		_spec.SetField(participant.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(participant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   participant.UserTable,
			Columns: []string{participant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_participants = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   participant.EventTable,
			Columns: []string{participant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_participants = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ParticipantCreateBulk is the builder for creating many Participant entities in bulk.
type ParticipantCreateBulk struct {
	config
	err      error
	builders []*ParticipantCreate
}

// Save creates the Participant entities in the database.
func (pcb *ParticipantCreateBulk) Save(ctx context.Context) ([]*Participant, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Participant, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParticipantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ParticipantCreateBulk) SaveX(ctx context.Context) []*Participant {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ParticipantCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ParticipantCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
