// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/matsuokashuhei/morrow-backend/ent/event"
	"github.com/matsuokashuhei/morrow-backend/ent/participant"
	"github.com/matsuokashuhei/morrow-backend/ent/schema"
	"github.com/matsuokashuhei/morrow-backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[6].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescUpdatedAt is the schema descriptor for updated_at field.
	eventDescUpdatedAt := eventFields[7].Descriptor()
	// event.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	event.DefaultUpdatedAt = eventDescUpdatedAt.Default.(func() time.Time)
	// event.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	event.UpdateDefaultUpdatedAt = eventDescUpdatedAt.UpdateDefault.(func() time.Time)
	participantFields := schema.Participant{}.Fields()
	_ = participantFields
	// participantDescJoinedAt is the schema descriptor for joined_at field.
	participantDescJoinedAt := participantFields[2].Descriptor()
	// participant.DefaultJoinedAt holds the default value on creation for the joined_at field.
	participant.DefaultJoinedAt = participantDescJoinedAt.Default.(func() time.Time)
	// participantDescUpdatedAt is the schema descriptor for updated_at field.
	participantDescUpdatedAt := participantFields[3].Descriptor()
	// participant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	participant.DefaultUpdatedAt = participantDescUpdatedAt.Default.(func() time.Time)
	// participant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	participant.UpdateDefaultUpdatedAt = participantDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
